language: "haskell"
install:
    - "cabal install HUnit async hspec bytestring contravariant hspec quickcheck-assertions"
    - "cabal configure --enable-tests"
    - "cabal build"
    - "cabal test"
    - "cabal install"
notifications:
    email: true
